"""change constants to enum

Revision ID: 58f319499174
Revises: fe84ba20e1a9
Create Date: 2024-10-06 18:15:15.534459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58f319499174'
down_revision: Union[str, None] = 'fe84ba20e1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status_enum', sa.Enum('proposed', 'booked', 'arrived', 'fulfilled', 'cancelled', 'noshow', 'entered_in_error', 'checked_in', 'waitlist', name='statuses'), nullable=False))
    op.drop_column('appointments', 'status')
    op.add_column('patients', sa.Column('gender_name', sa.Enum('male', 'female', 'other', 'unknown', name='genders'), nullable=False))
    op.drop_column('patients', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('gender', postgresql.ENUM('male', 'female', 'other', 'unknown', name='gender_name'), autoincrement=False, nullable=True))
    op.drop_column('patients', 'gender_name')
    op.add_column('appointments', sa.Column('status', postgresql.ENUM('proposed', 'pending', 'booked', 'arrived', 'fulfilled', 'cancelled', 'noshow', 'entered-in-error', 'checked-in', 'waitlist', name='status_enum'), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'status_enum')
    # ### end Alembic commands ###
