"""create tables

Revision ID: 897f6f133937
Revises:
Create Date: 2024-09-28 14:45:01.387603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '897f6f133937'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('patient_id', sa.String(), nullable=False),
                    sa.Column('identifier', sa.String(), nullable=True),
                    sa.Column('fullname', sa.String(), nullable=False),
                    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender_name'),
                              nullable=True),
                    sa.Column('birth_date', sa.DATE(), nullable=False),
                    sa.Column('address', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('patient_id')
                    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('resources',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('last_update', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('appointments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status',
                              sa.Enum('proposed', 'pending', 'booked', 'arrived', 'fulfilled', 'cancelled', 'noshow',
                                      'entered-in-error', 'checked-in', 'waitlist', name='status_enum'),
                              nullable=False),
                    sa.Column('service_details', sa.JSON(), nullable=True),
                    sa.Column('date_start', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('date_end', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('participants', sa.JSON(), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.Column('patient_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
                    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
