"""change enum statuses

Revision ID: e9f33a11918b
Revises: e2a9e34c3a1c
Create Date: 2024-10-07 16:47:57.450308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e9f33a11918b'
down_revision: Union[str, None] = 'e2a9e34c3a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_enum_values = ['PROPOSED', 'PENDING', 'BOOKED', 'ARRIVED', 'FULFILLED',
                   'CANCELLED', 'NOSHOW', 'ENTERED_IN_ERROR', 'CHECKED_IN', 'WAITLIST']

old_enum_value = ['proposed', 'pending', 'booked', 'arrived', 'fulfilled',
                  'cancelled', 'noshow', 'entered-in-error', 'checked-in', 'waitlist']


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"CREATE TYPE status_enum_temp AS ENUM ({', '.join([repr(value) for value in new_enum_values])});")
    op.alter_column('appointments', 'status',
                    existing_type=postgresql.ENUM(name='status_enum'),
                    type_=postgresql.ENUM(name='status_enum_temp'),
                    postgresql_using='status::text::status_enum_temp',
                    nullable=True)
    op.execute("DROP TYPE status_enum;")
    op.execute("ALTER TYPE status_enum_temp RENAME TO status_enum;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"CREATE TYPE status_enum_old AS ENUM ({', '.join([repr(value) for value in old_enum_value])});")
    op.alter_column('appointments', 'status',
                    existing_type=postgresql.ENUM(name='status_enum'),
                    type_=postgresql.ENUM(name='status_enum_old'),
                    postgresql_using='status::text::status_enum_old',
                    nullable=True)
    op.execute("DROP TYPE status_enum;")
    op.execute("ALTER TYPE status_enum_old RENAME TO status_enum;")
    # ### end Alembic commands ###
