"""add uniq field

Revision ID: fe84ba20e1a9
Revises: cf0e10151f72
Create Date: 2024-10-03 12:00:03.483636

"""
# mypy: ignore-errors
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe84ba20e1a9'
down_revision: Union[str, None] = 'cf0e10151f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'resources', ['type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    # ### end Alembic commands ###
